In [1]:
import numpy as np
import time

In [2]:
my_list = list(range(1_000_000))
start_time = time.time()
result_list = [x * 2 for x in my_list]
end_time = time.time()

In [3]:
print(f"파이썬 리스트 실행 시간: {end_time - start_time:.5f}초")

파이썬 리스트 실행 시간: 0.06401초


In [4]:
my_array = np.arange(1_000_000)
start_time = time.time()
result_array = my_array * 2
end_time = time.time()

In [5]:
print(f"넘파이 배열 실행 시간: {end_time - start_time:.5f}초")

넘파이 배열 실행 시간: 0.00464초


In [7]:
a=np.arange((1,2,3,4,5))

[1 2 3 4]


In [8]:
a

array([1, 2, 3, 4])

In [9]:
a = np.array([1, 2, 3, 4, 5])

In [10]:
print(a)

[1 2 3 4 5]


In [11]:
print(np.sum(a))

15


In [12]:
print(np.min(a))

1


In [13]:
a = np.array([10, 20, 30, 40, 50])

In [14]:
condition_mask = (a > 25)
filtered_array = a[condition_mask]

In [15]:
print(filtered_array)

[30 40 50]


In [16]:
a = np.array([10, 20, 30, 40, 50])

In [17]:
print(a(a>25))

TypeError: 'numpy.ndarray' object is not callable

In [18]:
print(a[a>25])

[30 40 50]


In [19]:
import numpy as np
# 비행 거리 배열 (단위: km)
distances = np.array([1, 2, 3, 5, 8])
# 각 비행 시 예상 풍속 배열 (단위: m/s)
windspeeds = np.array([0, 5, 10, 7, 12])

In [20]:
# 기본 배터리 소모율 (단위: %/km)
base_usage_rate = 10
# 풍속에 따른 추가 소모율 (단위: %/km)
additional_usage_rate = windspeeds

In [21]:
total_usage_rate = base_usage_rate + additional_usage_rate


In [22]:
battery_consumption = distances * total_usage_rate

In [23]:
print("비행 거리 (km):", distances)
print("풍속 (m/s):", windspeeds)
print("총 소모율 (%/km):", total_usage_rate)
print("예상 배터리 소모량 (%):", battery_consumption)

비행 거리 (km): [1 2 3 5 8]
풍속 (m/s): [ 0  5 10  7 12]
총 소모율 (%/km): [10 15 20 17 22]
예상 배터리 소모량 (%): [ 10  30  60  85 176]


In [28]:
import pandas as pd

# 'your_file.csv'를 실제 CSV 파일 경로 및 이름으로 변경해주세요.
# 예를 들어, 파일이 현재 작업 디렉토리에 있다면 'data.csv'처럼 사용합니다.
# df = pd.read_csv('data.csv')

df = pd.read_csv('Iris.csv')

# 데이터프레임의 상위 5행을 확인하여 성공적으로 불러왔는지 확인합니다.
print(df.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [29]:
print(df.head(10))

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa


In [30]:
print(df.tail(10))

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
140  141            6.7           3.1            5.6           2.4   
141  142            6.9           3.1            5.1           2.3   
142  143            5.8           2.7            5.1           1.9   
143  144            6.8           3.2            5.9           2.3   
144  145            6.7           3.3            5.7           2.5   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
140  Iris-virginica  
141  Iris-virginica  
142  Iris-virginica  
143  Iris-virginica  
144  Iris-virginica  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris

In [31]:
display(df)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [32]:
print(df['Id'])

0        1
1        2
2        3
3        4
4        5
      ... 
145    146
146    147
147    148
148    149
149    150
Name: Id, Length: 150, dtype: int64


In [33]:
print(df.tail(10))

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
140  141            6.7           3.1            5.6           2.4   
141  142            6.9           3.1            5.1           2.3   
142  143            5.8           2.7            5.1           1.9   
143  144            6.8           3.2            5.9           2.3   
144  145            6.7           3.3            5.7           2.5   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
140  Iris-virginica  
141  Iris-virginica  
142  Iris-virginica  
143  Iris-virginica  
144  Iris-virginica  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris

In [34]:
filtered_df = df[df['PetalLengthCm'] < 5]

In [35]:
display(filtered_df.head())

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [36]:
filtered_by_sepal_length = df[df['SepalLengthCm'] < 5]

In [37]:
display(filtered_by_sepal_length.head())

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa